networks:
  my_custom_network:
    name: my_custom_network
    driver: bridge

services:
  storage-service:
    build: .
    environment:
      SAGA_PORT: 5300
    ports:
      - "8081:8080"
    networks:
      - my_custom_network